version: '3'
services:
  app:
    build: ./project3-server
    ports:
      - "3200:3200"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./project3-server:/project3-server
  db:
    build: ./DB
